config/routes.rb
AppTrack::Application.routes.draw do
  devise_for :users

  resources :devices

   root :to => "devices#index"

end

app/models/device.rb
class Device < ActiveRecord::Base
  validates_presence_of :serial_number
  validates_presence_of :model_number
  validates_presence_of :tag
  validates_presence_of :type
  validates_presence_of :pool_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /devices
  # GET /devices.xml
  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.xml
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.xml
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.xml
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to(@device, :notice => 'Device was successfully created.') }
        format.xml  { render :xml => @device, :status => :created, :location => @device }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.xml
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to(@device, :notice => 'Device was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.xml
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to(devices_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.haml
= form_for @device do |f|
  -if @device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :serial_number
    = f.text_field :serial_number
  .field
    = f.label :model_number
    = f.text_field :model_number
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :tag
    = f.text_field :tag
  .field
    = f.label :user_id
    = f.text_field :user_id
  .field
    = f.label :pool_id
    = f.text_field :pool_id
  .actions
    = f.submit 'Save'

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%h1 Listing devices

%table
  %tr
    %th Serial number
    %th Model number
    %th Type
    %th Tag
    %th User
    %th Pool
    %th
    %th
    %th

  - @devices.each do |device|
    %tr
      %td= device.serial_number
      %td= device.model_number
      %td= device.type
      %td= device.tag
      %td= device.user_id
      %td= device.pool_id
      %td= link_to 'Show', device
      %td= link_to 'Edit', edit_device_path(device)
      %td= link_to 'Destroy', device, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Device', new_device_path

app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.haml
%p#notice= notice

%p
  %b Serial number:
  = @device.serial_number
%p
  %b Model number:
  = @device.model_number
%p
  %b Type:
  = @device.type
%p
  %b Tag:
  = @device.tag
%p
  %b User:
  = @device.user_id
%p
  %b Pool:
  = @device.pool_id

= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title AppTrack
    = stylesheet_link_tag :all, :recursive => true
    = javascript_include_tag :defaults, 'jquery/jquery.js', 'rails.js'
    = csrf_meta_tag
  %body
    #user_nav
      - if user_signed_in?
        Signed in as #{current_user.email}. Not you?
        \#{link_to "Sign out", destroy_user_session_path}
      - else
        = link_to "Sign up", new_user_registration_path
        or
        \#{link_to "Sign in", new_user_session_path}
    - flash.each do |name, msg|
      = content_tag :div, msg, :class => "#{name}"
    = yield